### ISSUE TITLE
Splunk python SDK no longer supported in cloud

### ISSUE THREAD

**Issue by johnberwick** [Kintyre/jmespath#29]
Can you please update the splunk python SDK to 1.6.16 or higher for cloud compatibility

**Comment by lowell80** [comment]
Scheduled.  Thanks John.

**Comment by lowell80** [comment]
Version 1.9.7 has been released with the latest libraries and some other structural updates.   Still waiting on splunkbase's validation process.  :-(

**Comment by lowell80** [comment]
It's available for release now, and somehow a test Splunk Cloud account I have just let me install it through self-service (even though the app name is already registered, so that's counter to behaviors I've seen in the past).

But it's working so I'm going to close this issue.
